// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuK6DcAYRiy-Weggj4wFf3QzT4N6mLByg',
    appId: '1:267892810055:web:79c3fc468deda6b1516c62',
    messagingSenderId: '267892810055',
    projectId: 'poststory-8f726',
    authDomain: 'poststory-8f726.firebaseapp.com',
    databaseURL: 'https://poststory-8f726-default-rtdb.firebaseio.com',
    storageBucket: 'poststory-8f726.appspot.com',
    measurementId: 'G-CQ3XGDSZYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdjBsnSSylMWK3siTrfYkipJdG9roUeTU',
    appId: '1:267892810055:android:de4ef2abda5fe727516c62',
    messagingSenderId: '267892810055',
    projectId: 'poststory-8f726',
    databaseURL: 'https://poststory-8f726-default-rtdb.firebaseio.com',
    storageBucket: 'poststory-8f726.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_QVad_oE17Dz6H5weLVz-8yj81FbJF9I',
    appId: '1:267892810055:ios:78a343f599d96cc1516c62',
    messagingSenderId: '267892810055',
    projectId: 'poststory-8f726',
    databaseURL: 'https://poststory-8f726-default-rtdb.firebaseio.com',
    storageBucket: 'poststory-8f726.appspot.com',
    androidClientId: '267892810055-bhc99som1j2ncg7hjvprumunpnu3ldjp.apps.googleusercontent.com',
    iosClientId: '267892810055-bgghkmj8jiio6egrop782rv43k2bieok.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_QVad_oE17Dz6H5weLVz-8yj81FbJF9I',
    appId: '1:267892810055:ios:78a343f599d96cc1516c62',
    messagingSenderId: '267892810055',
    projectId: 'poststory-8f726',
    databaseURL: 'https://poststory-8f726-default-rtdb.firebaseio.com',
    storageBucket: 'poststory-8f726.appspot.com',
    androidClientId: '267892810055-bhc99som1j2ncg7hjvprumunpnu3ldjp.apps.googleusercontent.com',
    iosClientId: '267892810055-bgghkmj8jiio6egrop782rv43k2bieok.apps.googleusercontent.com',
    iosBundleId: 'com.harshRajpurohit.weChat',
  );
}
